### ISSUE TITLE
be able to kill event loop

### ISSUE THREAD

**Issue by jrockway** [jrockway/anyevent-subprocess#3]
(Needs AnyEventX::Cancel.)

**Comment by hercynium** [comment]
I'm definitely interested in this one, as I wasn't aware it was an issue until I went hunting for some unexpected behavior!

If I can lend some tuits and be of help, let me know!

**Comment by jrockway** [comment]
Hey, sorry for not replying sooner.  The main issue I'm having with AnyEventX::Cancel is killing the EV loop after a fork.  Event and POE are fine, and nobody uses the others.  I talked to Marc (the EV author) a year or so ago, and he suggested just undef-ing the default loop in C after the fork so that a new loop would be created.  I tried this once, and it caused segfaults.  I tried it again a few releases later, and it caused less segfaults.  But now EV has been redesigned and there has been a new major release, so it will probably work.

If you want to take a look and try this, please fork AnyEventX::Cancel, implement this, and commit!  If your stuff works, I will release AX::Cancel and an AE::Subprocess that understands it ASAP!

Thanks for the offer of help, and please ping me on irc (irc.perl.org / jrockway) if you need anything.

**Comment by hercynium** [comment]
The code in the gist below seems to do the trick, though I have yet to test it in a complicated application. However, I'm going to need to find a good way to do it in a server I'm writing so I'll let you know if this works.

  https://gist.github.com/748834

I'm currently running with EV 4.01 and whatever the latest AnyEvent is. The EV::default_destroy() sub isn't documented in the POD but it's defined in EV.xs and appears to do what's needed. I'm hercynium on irc, btw.

**Comment by jrockway** [comment]
Wow, super excellent!  I tested and it works fine.  Would you please fork AnyEventX::Cancel and add your EV-cancelling code as a patch?  I will handle the test case, and then release to CPAN along with an AnyEvent::Subprocess delegate :)

I have been wanting this for a long time, and am 100% happy if only POE and EV are handled cleanly.  POE was easy, and it looks like EV is fine now too :)  Thanks!

**Comment by hercynium** [comment]
Great! I'll send the pull request immediately. It indeed seems to work -  my server had a heartbeat timer that was being cloned and was firing in the child. I initially fixed it with some nasty code and using this is _much_ cleaner!
